language: java
script:
 - mvn clean verify
after_success:
 - docker build -t noldorth/db /sample-application-db-changelog-job
 - docker build -t noldorth/http /sample-application-http-api-changelog-job
